# http server configuration
http:
  # listens on port
  port: ${HTTP_PORT|8090}
  cors:
    allowedHeaders:
      - "*"
    allowedOrigins:
      - "*"
    allowedMethods:
      - GET
      - POST
      - PUT
      - DELETE
      - OPTIONS
    debug: ${HTTP_CORS_DEBUG_ENABLED|false}
  # trace requests/responses
  trace: ${HTTP_TRACE_ENABLED|false}
  # http server write timeout
  write-timeout-sec: ${HTTP_WRITE_TIMEOUT_SEC|10}
  # http read write timeout
  read-timeout-sec: ${HTTP_READ_TIMEOUT_SEC|10}
  # http server write buffer size
  write-buffer-size-bytes: ${HTTP_WRITE_BUFFER_SIZE_BYTES|1024}
  # http server read buffer size
  read-buffer-size-bytes: ${HTTP_READ_BUFFER_SIZE_BYTES|1024}

auth:
  # session config
  session:
    # access token
    access-token:
      # secret
      secret: ${AUTH_ACCESS_TOKEN_SECRET|c78f90dbcbaa485db57f7b2d9c56143f}
      # expiration period in seconds
      expiration-period-sec: ${AUTH_ACCESS_TOKEN_EXPIRATION_SEC|9000}
    # refresh token
    refresh-token:
      # secret
      secret: ${AUTH_REFRESH_TOKEN_SECRET|c94f85dbcbaa345db57f7b2d9c38743f}
      # expiration period in seconds
      expiration-period-sec: ${AUTH_REFRESH_TOKEN_EXPIRATION_SEC|604800}
  # password policy
  password:
    # minimum len
    min-len: 6
  # user activation by email
  activation:
    # activation url
    url: ${AUTH_USER_ACTIVATION_URL|http://localhost:8090/api/auth/users/activation}
    # activation link live time
    ttl: ${AUTH_USER_ACTIVATION_TTL|3600}

communications:
  # email
  email:
    # smtp server host
    smtp-server: ${SMTP_HOST|localhost}
    # smtp server port
    smtp-port: ${SMTP_PORT|11025}
    # smtp user
    smtp-user: ${SMTP_USERNAME|mail@africarealty.io}
    # smtp password
    smtp-password: ${SMTP_PASSWORD|}
    # smtp from
    smtp-from: ${SMTP_FROM|noreply@africarealty.io}

# storage configurations
storages:
  # aerospike
  aero:
    host: ${AERO_HOST|localhost}
    port: ${AERO_PORT|30000}
  # pg client
  pg:
    # local path to migration folder
    mig-path: ${ARROOT|}/africarealty/src/db/migrations
    # db master config
    master:
      # database name
      dbname: ${AR_DB_MASTER_NAME|africarealty}
      # db username
      user: africarealty
      # db password
      password: ${AR_DB_MASTER_PASSWORD|africarealty}
      # db port
      port: ${AR_DB_MASTER_PORT|25432}
      # host for master (read-write) database
      host: ${AR_DB_MASTER_HOST|localhost}

# NATS client
nats:
  # host
  host: ${NATS_HOST|localhost}
  # port
  port: ${NATS_PORT|14222}
  # cluster Id
  clusterId: ${NATS_CLUSTER_ID|test-cluster}

# logging configuration
log:
  # level
  level: ${AR_LOG_LEVEL|trace}
  # output format (plain, json)
  format: ${AR_LOG_FORMAT|plain}
  # if true, outputs context info
  context: ${AR_LOG_CONTEXT|true}
  # if true, outputs running service instance info
  service: ${AR_LOG_SERVICE|true}

# sdk config
sdk:
  # sdk base url
  url: ${SDK_URL|http://localhost:8090}
  # logging configuration
  log:
    # level
    level: ${SDK_LOG_LEVEL|trace}
    # output format (plain, json)
    format: ${SDK_LOG_FORMAT|plain}
    # if true, outputs context info
    context: ${SDK_LOG_CONTEXT|true}
    # if true, outputs running service instance info
    service: ${SDK_LOG_SERVICE|true}

# integration test config
tests:
  # sdk user
  user: ${SDK_USER|admin}
  # password
  password: ${SDK_PASSWORD|admin}