version: "3"

services:

  aerospike:
    container_name: ar-aerospike
    networks:
      - ar
    image: aerospike/aerospike-server
    expose:
      - 30000
      - 30001
      - 30002
    ports:
      - "30000:3000"
      - "30001:3001"
      - "30002:3002"
    environment:
      - NAMESPACE=memcache
    volumes:
      - /var/africarealty/docker/volumes/aerospike/data:/opt/aerospike/data
      - /var/africarealty/docker/volumes/aerospike/etc:/opt/aerospike/etc

  pg:
    container_name: ar-pg
    networks:
      - ar
    build:
      context: ./infra/pg
    read_only: true
    ports:
      - "25432:5432"
    volumes:
      - /var/africarealty/docker/volumes/pg/data:/var/lib/postgresql/data
      - /etc/localtime:/etc/localtime:ro
    environment:
      - POSTGRES_USER=admin
      - POSTGRES_PASSWORD=admin
      - POSTGRES_DB=africarealty

  mailhog:
    container_name: ar-mailhog
    image: "mailhog/mailhog"
    ports:
      - "10025:1025"
      - "80025:8025"
    networks:
      - ar

  minio:
    container_name: ar-minio
    image: "minio/minio:RELEASE.2021-06-17T00-10-46Z"
    command: "server /data"
    ports:
      - 18062:9000
    networks:
      - ar
    volumes:
      - /var/africarealty/docker/volumes/minio:/data
    environment:
      MINIO_ROOT_USER: minioaccesskey
      MINIO_ROOT_PASSWORD: miniosecretkey
    #      MINIO_SSE_MASTER_KEY: "my-minio-key:6368616e676520746869732070617373776f726420746f206120736563726574"
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:9000/minio/health/live" ]
      interval: 30s
      timeout: 20s
      retries: 3

  elasticsearch:
    container_name: ar-es
    networks:
      - ar
    image: elasticsearch:7.10.1
    ports:
      - "19200:9200"
    user: "1000:1000"
    environment:
      - discovery.type=single-node
      - cluster.name=elasticsearch
      - "ES_JAVA_OPTS=-Xms512m -Xmx512m"
    volumes:
      - /var/africarealty/docker/volumes/es:/usr/share/elasticsearch/data

  elasticHQ:
    container_name: ar-eshq
    networks:
      - ar
    ports:
      - "15000:5000"
    image: elastichq/elasticsearch-hq
    environment:
      - HQ_DEFAULT_URL=http://elasticsearch:19200
    depends_on:
      - elasticsearch

  nats:
    container_name: ar-stan
    networks:
      - ar
    ports:
      - "14222:4222"
      - "18222:8222"
    image: nats-streaming
    expose:
      - 14222
      - 18222
    command:
      - "--debug"
      - "--store"
      - file
      - "--dir"
      - /data/msg
      - "--http_port"
      - "8222"
      - "--port"
      - "4222"
    volumes:
      - /var/africarealty/docker/volumes/nats/data:/data

networks:
  ar:
    external: true
