// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	listener "github.com/africarealty/server/src/kit/queue/listener"
	mock "github.com/stretchr/testify/mock"
)

// Builder is an autogenerated mock type for the Builder type
type Builder struct {
	mock.Mock
}

// Add provides a mock function with given fields:
func (_m *Builder) Add() {
	_m.Called()
}

// AtLeastOnce provides a mock function with given fields: durableId
func (_m *Builder) AtLeastOnce(durableId string) listener.Builder {
	ret := _m.Called(durableId)

	var r0 listener.Builder
	if rf, ok := ret.Get(0).(func(string) listener.Builder); ok {
		r0 = rf(durableId)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.Builder)
		}
	}

	return r0
}

// AtMostOnce provides a mock function with given fields:
func (_m *Builder) AtMostOnce() listener.Builder {
	ret := _m.Called()

	var r0 listener.Builder
	if rf, ok := ret.Get(0).(func() listener.Builder); ok {
		r0 = rf()
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.Builder)
		}
	}

	return r0
}

// WithHandler provides a mock function with given fields: _a0
func (_m *Builder) WithHandler(_a0 listener.QueueMessageHandler) listener.Builder {
	ret := _m.Called(_a0)

	var r0 listener.Builder
	if rf, ok := ret.Get(0).(func(listener.QueueMessageHandler) listener.Builder); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.Builder)
		}
	}

	return r0
}

// WithLoadBalancing provides a mock function with given fields: lbGroup
func (_m *Builder) WithLoadBalancing(lbGroup string) listener.Builder {
	ret := _m.Called(lbGroup)

	var r0 listener.Builder
	if rf, ok := ret.Get(0).(func(string) listener.Builder); ok {
		r0 = rf(lbGroup)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(listener.Builder)
		}
	}

	return r0
}
