// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import (
	context "context"

	domain "github.com/africarealty/server/src/domain"
	mock "github.com/stretchr/testify/mock"
)

// EmailStorage is an autogenerated mock type for the EmailStorage type
type EmailStorage struct {
	mock.Mock
}

// CreateEmail provides a mock function with given fields: ctx, requests
func (_m *EmailStorage) CreateEmail(ctx context.Context, requests *domain.Email) error {
	ret := _m.Called(ctx, requests)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Email) error); ok {
		r0 = rf(ctx, requests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

// UpdateEmail provides a mock function with given fields: ctx, requests
func (_m *EmailStorage) UpdateEmail(ctx context.Context, requests *domain.Email) error {
	ret := _m.Called(ctx, requests)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, *domain.Email) error); ok {
		r0 = rf(ctx, requests)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewEmailStorage interface {
	mock.TestingT
	Cleanup(func())
}

// NewEmailStorage creates a new instance of EmailStorage. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEmailStorage(t mockConstructorTestingTNewEmailStorage) *EmailStorage {
	mock := &EmailStorage{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
