// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// ErrorHook is an autogenerated mock type for the ErrorHook type
type ErrorHook struct {
	mock.Mock
}

// Error provides a mock function with given fields: err
func (_m *ErrorHook) Error(err error) {
	_m.Called(err)
}
