// Code generated by mockery 2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// EventHandler is an autogenerated mock type for the EventHandler type
type EventHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields:
func (_m *EventHandler) Execute() {
	_m.Called()
}

type mockConstructorTestingTNewEventHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewEventHandler creates a new instance of EventHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewEventHandler(t mockConstructorTestingTNewEventHandler) *EventHandler {
	mock := &EventHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
