// Code generated by mockery v2.14.0. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// QueueMessageHandler is an autogenerated mock type for the QueueMessageHandler type
type QueueMessageHandler struct {
	mock.Mock
}

// Execute provides a mock function with given fields: payload
func (_m *QueueMessageHandler) Execute(payload []byte) error {
	ret := _m.Called(payload)

	var r0 error
	if rf, ok := ret.Get(0).(func([]byte) error); ok {
		r0 = rf(payload)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewQueueMessageHandler interface {
	mock.TestingT
	Cleanup(func())
}

// NewQueueMessageHandler creates a new instance of QueueMessageHandler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewQueueMessageHandler(t mockConstructorTestingTNewQueueMessageHandler) *QueueMessageHandler {
	mock := &QueueMessageHandler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
