// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	auth "github.com/africarealty/server/src/kit/auth"

	http "net/http"

	mock "github.com/stretchr/testify/mock"
)

// ResourcePolicy is an autogenerated mock type for the ResourcePolicy type
type ResourcePolicy struct {
	mock.Mock
}

// Resolve provides a mock function with given fields: ctx, r
func (_m *ResourcePolicy) Resolve(ctx context.Context, r *http.Request) (*auth.AuthorizationResource, error) {
	ret := _m.Called(ctx, r)

	var r0 *auth.AuthorizationResource
	if rf, ok := ret.Get(0).(func(context.Context, *http.Request) *auth.AuthorizationResource); ok {
		r0 = rf(ctx, r)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(*auth.AuthorizationResource)
		}
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, *http.Request) error); ok {
		r1 = rf(ctx, r)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}
