// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	context "context"

	mock "github.com/stretchr/testify/mock"
)

// Telegram is an autogenerated mock type for the Telegram type
type Telegram struct {
	mock.Mock
}

// Send provides a mock function with given fields: ctx, bot, text, channel
func (_m *Telegram) Send(ctx context.Context, bot string, text string, channel int) error {
	ret := _m.Called(ctx, bot, text, channel)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, string, string, int) error); ok {
		r0 = rf(ctx, bot, text, channel)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
