// Code generated by mockery 2.9.0. DO NOT EDIT.

package mocks

import (
	mux "github.com/gorilla/mux"
	mock "github.com/stretchr/testify/mock"

	websocket "github.com/gorilla/websocket"
)

// WsUpgrader is an autogenerated mock type for the WsUpgrader type
type WsUpgrader struct {
	mock.Mock
}

// Set provides a mock function with given fields: router, upgrader
func (_m *WsUpgrader) Set(router *mux.Router, upgrader *websocket.Upgrader) {
	_m.Called(router, upgrader)
}
